# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- add-commandline-options

pool:
  vmImage: ubuntu-latest

steps:

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(Build.SourcesDirectory)'
    
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '$(Build.SourcesDirectory)'
    customCommand: 'audit fix'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(Build.SourcesDirectory)/build'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '$(Build.SourcesDirectory)/build'
    customCommand: 'audit fix''

- script: |
    $(Build.SourcesDirectory)/build.sh --distribution $(DistributionName) --method $(AuthMethod) --tenant $(TenantId) --client-id $(ClientId) --client-secret $(CLIENTSECRET) --redirect-uri $(RedirectURI) --session-duration $(SessionDuration) --authz $(AuthZType) --json-user-lookup $(JsonUsernameLookup) 
    ls $(Build.SourcesDirectory)
  displayName: 'Run a multi-line script'

